language: python
python:
  - "3.7"
compiler:
  - gcc
  
stages:
- test
- name: coverage
  if: branch = master AND type != pull_request
- name: deploy
  if: tag IS present
  
cache:
    directories:
     - $HOME/.buildozer/
     
before_install:
# most of the following is taken from https://buildozer.readthedocs.io/en/latest/installation.html
  - sudo apt-get update
  - sudo apt-get install -y libgl1-mesa-dev git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake
  - pip install --upgrade cython virtualenv
  - pip install --upgrade buildozer
  - PATH=$PATH:~/.local/bin/
  - git clone -b fix-pyproj-url https://github.com/joergbrech/python-for-android.git /home/travis/build/joergbrech/python-for-android # temporarily use my branch of p4a with fixed url. PR in progress
  
install:
  - pip install -r requirements.txt
  - pip install -e .
  
before_script:
# workaround to enforce openjdk8 on xenial
# from https://travis-ci.community/t/oracle-jdk-11-and-10-are-pre-installed-not-the-openjdk-builds/785/3
  - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
  - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  - java -version
  
script:
  - make test
  - travis_wait 60 make apk # remove this as soon as building APKs on Travis works. This should either be a seperate job, or only be done on deployment

jobs:
  include:
    - stage: coverage
      python: "3.6"
      install: 
        - pip install -r requirements.txt
        - pip install coverage codecov
        - pip install -e .
      script: 
        - make coverage
      after_success: codecov
    - stage: deploy
      python: "3.6"
      script: 
        - make deploy
      #TODO: Sign, upload to Github Releases and maybe even to Play Store if possible
