language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
compiler:
  - gcc
  
stages:
- test
- name: coverage
  if: branch = master AND type != pull_request
- name: deploy
  if: tag IS present

before_install:
  - sudo apt-get install libgl1-mesa-dev

script:
  - pip install -e .

jobs:
  include:
    - stage: test
      script: 
        - make test
        - make apk
    - stage: coverage
      python: "3.6"
      install: pip install coverage codecov
      script: make coverage
      after_success: codecov
    - stage: deploy
      python: "3.6"
      script: make deploy
      #TODO: Upload to Github Releases and maybe even Play Store
