language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  
compiler:
  - gcc

install:
  - pip install -r requirements.txt
  - pip install -e .

docs:
  - make docs
  
test:
  - make test
  
