language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
compiler:
  - gcc
  
stages:
- test
- name: coverage
  if: branch = master AND type != pull_request
- name: deploy
  if: tag IS present

jobs:
  include:
    - stage: test
      script: 
        - sudo apt-get install libgl1-mesa-dev
        - pip install -e .
        - make test
        - pip install cython
        - pip install buildozer
        - make apk
    - stage: coverage
      python: "3.6"
      install: pip install coverage codecov
      script: 
        - sudo apt-get install libgl1-mesa-dev
        - pip install -e .
        - make coverage
      after_success: codecov
    - stage: deploy
      python: "3.6"
      script: 
        - sudo apt-get install libgl1-mesa-dev
        - pip install -e .
        - pip install cython==0.23
        - pip install buildozer
        - make deploy
      #TODO: Upload to Github Releases and maybe even Play Store
