language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
compiler:
  - gcc
jdk:
  - openjdk8
  
stages:
- test
- name: coverage
  if: branch = master AND type != pull_request
- name: deploy
  if: tag IS present
  
install:
  - sudo apt-get install libgl1-mesa-dev
  - pip install -r requirements.txt
  - pip install cython buildozer
  - pip install -e .
  
before_script:
  - java --version
  
script:
  - make test
  - make apk

jobs:
  include:
    - stage: coverage
      python: "3.6"
      install: 
        - pip install -r requirements.txt
        - pip install coverage codecov
        - pip install -e .
      script: 
        - make coverage
      after_success: codecov
    - stage: deploy
      python: "3.6"
      script: 
        - make deploy
      #TODO: Upload to Github Releases and maybe even Play Store
