language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
os:
  - linux
#  - osx  ## uncomment if one day Travis support python on Mac
compiler:
  - gcc
  
stages:
- test
- name: coverage
  if: branch = master AND type != pull_request
- name: doc
- name: deploy
  if: tag IS present
script: skip
  
before_install:
  - sudo apt-get install libgl1-mesa-dev
  
jobs:
  include:
    - stage: test
      script: make test
    - stage: coverage
      os: linux
      python: "3.6"
      install: pip install pytest-cov coverage codecov
      script: make coverage
      after_success: codecov
    - stage: doc
      os: linux
      python: "3.6"
      script: make docs
      #TODO: publish to github pages and readthedocs.io
    - stage: deploy
      os: linux
      script: make deploy
      #TODO: Upload to Github Releases and maybe even Play Store
