language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
os:
  - linux
  - osx
compiler:
  - gcc
  
before_install:
  - sudo apt-get install libgl1-mesa-dev
  
jobs:
  include:
    - stage: test
      script: make test
    - stage: coverage
      os: linux
      python: "3.6"
      script: make coverage
      #TODO: connect to codecov.io
    - stage: doc
      os: linux
      python: "3.6"
      if: branch = master AND type != pull_request
      script: make docs
      #TODO: publish to github pages and readthedocs.io
    - stage: deploy
      os: linux
      script: make deploy
      #TODO: Upload to Github Releases and maybe even Play Store
